Lab 23: CI/CD Pipeline Implementation with Jenkins Agents and Shared Libraries

diff --git a/ci-cd/lab23/Jenkins_App/Jenkinsfile b/ci-cd/lab23/Jenkins_App/Jenkinsfile
--- a/ci-cd/lab23/Jenkins_App/Jenkinsfile
+++ b/ci-cd/lab23/Jenkins_App/Jenkinsfile
@@ -33,12 +33,12 @@ pipeline{
                  echo "Scanning Docker image with Trivy..."
 
                  sh '''
-                   trivy image $IMAGE_NAME:$BUILD_NUMBER \
-                   --severity HIGH,CRITICAL \
-                   --scanners vuln \
-                   --timeout 45m \
-                   --format json \
-                   -o trivy-report.json || true
+                //    trivy image $IMAGE_NAME:$BUILD_NUMBER \
+                //    --severity HIGH,CRITICAL \
+                //    --scanners vuln \
+                //    --timeout 45m \
+                //    --format json \
+                //    -o trivy-report.json || true
 
                    trivy image $IMAGE_NAME:$BUILD_NUMBER \
                    --scanners vuln \
@@ -47,20 +47,20 @@ pipeline{
                    -o trivy-report.html || true
                  '''
 
-                //  if (!fileExists('trivy-report.json')) {
-                //      error "Trivy scan failed: JSON report not generated"
-                //  }
+                 if (!fileExists('trivy-report.json')) {
+                     error "Trivy scan failed: JSON report not generated"
+                 }
 
-                //  def vulnCount = sh(
-                //      script: "jq '[.Results[].Vulnerabilities[]?] | length' trivy-report.json",
-                //      returnStdout: true
-                //  ).trim()
+                 def vulnCount = sh(
+                     script: "jq '[.Results[].Vulnerabilities[]?] | length' trivy-report.json",
+                     returnStdout: true
+                 ).trim()
 
-                //  echo "Vulnerabilities found: ${vulnCount}"
+                 echo "Vulnerabilities found: ${vulnCount}"
 
-                //  if (vulnCount.toInteger() > 0) {
-                //      error "Security gate failed: HIGH or CRITICAL vulnerabilities detected"
-                //  }
+                 if (vulnCount.toInteger() > 0) {
+                     error "Security gate failed: HIGH or CRITICAL vulnerabilities detected"
+                 }
              }
          }
             }       
